# NumPy Lab for Cloud Machine Learning

Question 1 <br> Numerical Analysis Exercises using NumPy – Rainfall Dataset:
The objective of the exercises is to familiarize yourself with the use of NumPy. These excises are mainly based on rainfall data in Cork for each month over the past half century. In the folder you will find a file called CorkRainfall.txt and a file called DublinRainfall.txt. This is a space delimited file.
Each line of the file contains the following precipitation information pertaining to a specific month and year:
> Year<br>
> Month (1 = Jan, 2 = Feb, 3 = March, etc. ) <br>
> Total Rainfall (Millimetres)<br>
> Most Rainfall in a Day (Millimetres)<br>
> Rain days (0.2mm or More) (Number)<br>

## Import the numpy library

* Make sure to install the library from the pipy using pip install numpy

In [2]:
import numpy as np

## Imprt the data to numpy array

* Data is copied in the current working directory

In [3]:
cork_rain_rawdata = np.genfromtxt("CorkRainfall.txt", dtype=float, delimiter=" ")

In [341]:
print(type(cork_rain_rawdata))

<class 'numpy.ndarray'>


In [347]:
del b


In [8]:
print(cork_rain_rawdata)
print("Single element", end=" : ")
print(cork_rain_rawdata[0,0])

[[1.962e+03 1.000e+00 1.346e+02 1.250e+01 2.200e+01]
 [1.962e+03 2.000e+00 7.720e+01 1.120e+01 1.700e+01]
 [1.962e+03 3.000e+00 7.360e+01 1.340e+01 1.300e+01]
 ...
 [2.011e+03 1.000e+01 9.180e+01 2.440e+01 2.200e+01]
 [2.011e+03 1.100e+01 1.486e+02 3.520e+01 2.300e+01]
 [2.011e+03 1.200e+01 8.710e+01 2.200e+01 2.600e+01]]
Single element : 1962.0


* Print out the max ‘Most Rainfall in a Day’ value and the average ‘Most Rainfall in a Day’ value for the Cork data (that is, obtain the maximum value contained in this column of data and the average value in this column of data).

In [12]:
avg_rain_cork = np.mean(cork_rain_rawdata[:,[4]])

In [13]:
print("The average most Rainfall in a Day : ", round(avg_rain_cork,3) )

The average most Rainfall in a Day :  17.503


In [14]:
most_rainday_cork = cork_rain_rawdata[:,[4]]
most_rainday_cork = np.append(most_rainday_cork, [[0]])

In [15]:
print("The max most Rainfall in a Day : ", max(most_rainday_cork) )

The max most Rainfall in a Day :  29.0


* Display all unique years for which there is data in the dataset (you can use np.unique) Ask the user to select a specific year and output the total number of Rain Days per month for that year (that is, add up all the total number of Rain Days column for each month of that year).

In [16]:
cork_rain_year = cork_rain_rawdata[:, [0]]

In [18]:
cork_rain_year_unique = np.unique(cork_rain_year)

In [19]:
print(cork_rain_year_unique)

[1962. 1963. 1964. 1965. 1966. 1967. 1968. 1969. 1970. 1971. 1972. 1973.
 1974. 1975. 1976. 1977. 1978. 1979. 1980. 1981. 1982. 1983. 1984. 1985.
 1986. 1987. 1988. 1989. 1990. 1991. 1992. 1993. 1994. 1995. 1996. 1997.
 1998. 1999. 2000. 2001. 2002. 2003. 2004. 2005. 2006. 2007. 2008. 2009.
 2010. 2011.]


In [95]:
user_year = int(input(f"Enter the year from {int(cork_rain_year_unique[0])} to {int(cork_rain_year_unique[-1])} : "))

In [96]:
user_year_data = []
for e in cork_rain_rawdata:
    if e[0] == user_year:
        print(e)
        user_year_data.append(e[4])


[1.981e+03 1.000e+00 4.180e+01 8.400e+00 1.600e+01]
[1981.     2.    97.    18.2   16. ]
[1981.     3.   213.5   29.    22. ]
[1981.     4.    30.3   17.     8. ]
[1981.     5.   216.4   30.5   26. ]
[1981.     6.    74.1   15.6   14. ]
[1981.     7.    36.2   13.8   17. ]
[1981.     8.    18.7    7.9    8. ]
[1981.     9.   169.1   27.6   23. ]
[1981.    10.    79.5   19.1   23. ]
[1981.    11.   106.7   21.6   19. ]
[1981.    12.   168.5   52.2   18. ]


In [97]:
print(f"Total number of Rain Days of {user_year} is {np.sum(user_year_data)} days.")

Total number of Rain Days of 1981 is 210.0 days.


* Calculate the wettest month of the year in Cork based on the “Total Rainfall” value. The month that has the highest cumulative “Total Rainfall” value across all years should be classified as the wettest. Your code should print out the month and the cumulative total rainfall value for that month.

In [100]:
most_total_rainfall = cork_rain_rawdata[:, 2]

In [121]:
months = {1:"Jan", 2:"Feb", 3:"Mar", 4:"Apr", 5:"May", 6:"June", 7:"Jul", 8:"Aug", 9:"Sep", 10:"Oct", 11:"Nov", 12:"Dec" }

In [125]:
for e in cork_rain_rawdata:
    if e[2] == max(most_total_rainfall):
        print(f"The most raifall is in the {months[e[1]]} month of year {int(e[0])}. A total of {e[2]} Millimetres Rainfall.")

The most raifall is in the Jan month of year 1974. A total of 340.9 Millimetres Rainfall.


* This question focuses on the Number of Rain days column. The user is asked to enter
a maximum threshold value for the number of rain days. Your code should then
output the percentage of the time (percentage of rows in the dataset) where the
number of rain days is less than or equal to the threshold value.For example, if a user enters a maximum threshold value of 6, then your code should
output the percentage of rows where the number of rain days fell between the threshold value of 6.

In [202]:
user_imp = int(input("Enter the threshold value to analyse the data: "))

In [132]:
print(user_imp)

7


In [203]:
cork_rain_days = cork_rain_rawdata[:,4]

In [139]:
print(len(cork_rain_days))

600


In [204]:
threshol_filter = cork_rain_days <= user_imp

In [205]:
cork_rain_days_threshold = np.array(cork_rain_days[threshol_filter])

In [209]:
print(len(cork_rain_days_threshold))

326


In [208]:
print(f"There is {round(len(cork_rain_days_threshold)/len(cork_rain_days)*100,2)} % Rain Days between the threshold of {user_imp} Rain days.")

There is 54.33 % Rain Days between the threshold of 18 Rain days.


* Calculate the average ‘total rainfall’ value for the summer months (June, July and August) and the Autumn months (Sept, Oct, Nov).


In [281]:
all_summer_rainfall = []
for e in cork_rain_rawdata:
    if e[1] == 6:
        all_summer_rainfall.append(e[2])
    elif e[1] == 7:
        all_summer_rainfall.append(e[2])
    elif e[1] == 8:
        all_summer_rainfall.append(e[2])


In [282]:
all_autumn_rainfall = []
for e in cork_rain_rawdata:
    if e[1] == 9:
        all_autumn_rainfall.append(e[2])
    elif e[1] == 10:
        all_autumn_rainfall.append(e[2])
    elif e[1] == 11:
        all_autumn_rainfall.append(e[2])

In [357]:
all_autumn_rainfall = np.array(all_autumn_rainfall)

<class 'numpy.ndarray'>


In [356]:
print(f"The average rainfall from {int(cork_rain_year_unique[0])} to {int(cork_rain_year_unique[-1])} ({len(cork_rain_year_unique)} years) for the Summer months are {round(np.mean(all_summer_rainfall),2)} millimetres and Autumn months are {round(np.mean(all_autumn_rainfall),2)} millimetres")

The average rainfall from 1962 to 2011 (50 years) for the Summer months are 80.04 millimetres and Autumn months are 114.46 millimetres


* Read in the contents of the file DublinRainfall.txt into a NumPy array. Append the all rows from the Dublin array to the Cork NumPy array. Calculate the average number
of raindays for the new array and write the new NumPy array to a CSV file.

In [313]:
dublin_rain_rawdata = np.genfromtxt("DublinRainfall.txt", dtype=float, delimiter=" ")

In [314]:
print(dublin_rain_rawdata)

[[1.962e+03 1.000e+00 4.110e+01 7.100e+00 1.600e+01]
 [1.962e+03 2.000e+00 2.670e+01 5.700e+00 1.400e+01]
 [1.962e+03 3.000e+00 5.360e+01 1.510e+01 1.300e+01]
 ...
 [2.011e+03 1.000e+01 1.474e+02 7.130e+01 1.800e+01]
 [2.011e+03 1.100e+01 4.850e+01 1.170e+01 1.100e+01]
 [2.011e+03 1.200e+01 5.220e+01 5.200e+00 2.300e+01]]


In [332]:
dublin_cork_rain_rawdata = np.append(cork_rain_rawdata,dublin_rain_rawdata,axis=0)


In [335]:
print(len(dublin_cork_rain_rawdata))

1200


In [340]:
print(f"The average rain day for Dublin and Cork is {round(np.mean(dublin_cork_rain_rawdata[:,4]),2)}")

The average rain day for Dublin and Cork is 16.7
