In [6]:
import sys
import numpy as np

In [4]:
print(sys.version)

3.10.8 (main, Oct 13 2022, 20:51:03) [Clang 10.0.1 (clang-1001.0.46.4)]


In [7]:
import time

In [9]:
startPython = int(round(time.time() * 1000))

In [11]:
print(startPython)

1675607639527


In [12]:
a = list(range(10000000))
b = list(range(10000000))
c = []

In [14]:
for i in range(len(a)):
    c.append(a[i] + b[i])

stopPython = int(round(time.time()* 1000))

In [16]:
print(stopPython - startPython)
print(stopPython)

170149
1675607809676


In [17]:
a = np.arange(10000000, dtype=int)
b = np.arange(10000000, dtype=int)

c = a + b

stopNumpy = int(round(time.time()* 1000))


In [18]:
print(stopNumpy - startPython)


349063


In [19]:
print((stopNumpy - stopPython)/(stopPython - startPython))

1.0515136733098638


In [20]:
arr = np.array([5.5, 45.6, 3.2], float)

In [21]:
print(arr[0])

5.5


In [22]:
arr[0] = 5

In [23]:
print(arr[0])

5.0


In [24]:
print(arr)

[ 5.  45.6  3.2]


In [25]:
arr = np.array([[1,2,3], [4,5,6]], float)

In [26]:
print(arr[0])

[1. 2. 3.]


In [27]:
print(arr[0,0])

1.0


In [34]:
print(arr[1,2])

6.0


In [35]:
arr[0,1] = 12.2

In [36]:
print(arr)

[[ 1.  12.2  3. ]
 [ 4.   5.   6. ]]


In [37]:
print(arr[1])

[4. 5. 6.]


In [38]:
arr[0]=12.2

In [39]:
print(arr)

[[12.2 12.2 12.2]
 [ 4.   5.   6. ]]


In [40]:
arr[0]=1,2,3

In [41]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [54]:
print(arr[0,1:3],[1])

[2. 3.] [1]


In [68]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]], float)

In [74]:
print("firtst", arr[0:1, 0:4])

firtst [[1. 2. 3. 4.]]


In [82]:
print("Second", arr[0:3, 0:4:2])

Second [[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]]


In [86]:
print("Third", arr[:, 0:3])

Third [[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 9. 10. 11.]]


In [85]:
print("Fourth", arr[:, [0,3]])

Fourth [[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]]


In [87]:
data = np.array([[1, 2, 3], [2, 4, 5], [4, 5, 7],[6, 2, 3]], float)

In [88]:
resultA = data[:, 0:3]

In [89]:
resultA[0] = 200

In [90]:
print(data)
print(resultA)

[[200. 200. 200.]
 [  2.   4.   5.]
 [  4.   5.   7.]
 [  6.   2.   3.]]
[[200. 200. 200.]
 [  2.   4.   5.]
 [  4.   5.   7.]
 [  6.   2.   3.]]


In [91]:
print(len(arr))

3


In [92]:
print(len(arr[0]))

4


In [93]:
arr = np.arange(50)

In [94]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [95]:
print(len(arr))

50


In [105]:
arr2 = np.resize(arr, (10,5))

In [106]:
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [107]:
np.savetxt("numbers.txt", arr2, fmt="%d", delimiter=",")

In [110]:
data = np.genfromtxt("numbers.txt", delimiter=",")

In [113]:
print(data)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]]


In [114]:
data = np.array([[1, 2, 3], [2, 4, 5], [4, 5, 7],[6, 2, 3]], float)

In [117]:
data=np.append(arr, [[]])

In [118]:
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54]


In [134]:
arr = np.array([[1, 2, 3], [4, 5, 6]], float)
print (arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [135]:
arr1 = np.append(arr, [[7],[8]], axis=1)

In [136]:
print(arr)
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3. 7.]
 [4. 5. 6. 8.]]


In [137]:
print(np.sum(arr1))

36.0


In [138]:
arr = np.array([[1, 2, 3], [4, 5, 6]], float)

In [140]:
print(np.sum(arr))

21.0


In [142]:
arr1 = np.array([[1, 2, 4],[3, 4, 2]], float)

In [144]:
print(np.sum(arr1))
print(np.product(arr1))

16.0
192.0


In [146]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]], float)

In [147]:
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [148]:
print(np.product(arr2))

362880.0


In [156]:
print(np.sum(arr2))

45.0


In [158]:
print(np.mean(arr2, axis=1))

[2. 5. 8.]


In [160]:
arr1 = np.array([[10,20], [30, 40]], float)
arr2 = np.array([[1,2], [3,4]], float)

In [161]:
print(arr1+arr2)

[[11. 22.]
 [33. 44.]]


In [162]:
print(arr1*arr2)

[[ 10.  40.]
 [ 90. 160.]]


In [165]:
print(arr2/2)

[[0.5 1. ]
 [1.5 2. ]]


In [1]:
pwd

'/Users/libintom/Documents/devopslibin/python/numpypandas'

In [4]:
import numpy as np

In [32]:
corkrain = np.genfromtxt("CorkRainfall.txt", dtype=float, delimiter=" ")

In [30]:
del corkrain

In [43]:
avg_rain_cork = np.mean(corkrain[:,[4]])

In [49]:
print("The average most Rainfall in a Day : ", round(avg_rain_cork,3) )

The average most Rainfall in a Day :  17.503


In [61]:
most_rainday_cork = corkrain[:,[4]]
most_rainday_cork = np.append(most_rainday_cork, [[0]])
print(most_rainday_cork)


[22. 17. 13. 17. 16. 11. 15. 19. 19. 12. 14. 18. 13. 11. 25. 20. 19. 15.
 14. 22. 16. 21. 24. 17. 17. 19. 20. 20. 21. 16. 16. 16. 17. 19. 15. 19.
 19.  6. 17. 19. 19. 20. 17. 17. 19. 12. 22. 23. 21. 27. 17. 21. 17. 19.
 10. 19. 13. 19. 17. 23. 17. 18. 17.  7. 25.  7. 19. 18. 20. 25. 17. 17.
 20. 11. 14. 18. 16. 15.  7. 11. 21. 23. 23. 20. 21. 22. 13. 14. 20. 12.
  8. 11. 12. 18. 19. 21. 19. 20. 18. 20. 10. 11. 15.  7. 23. 16. 21. 13.
 24. 12. 15.  5. 15. 14. 11. 18. 12. 20. 16. 17. 22. 22. 20. 14. 22. 19.
 13. 12.  4. 15. 18. 25. 17. 20. 12. 11. 23.  9. 14. 18. 16. 12. 21. 19.
 28. 20.  8.  8. 16. 11. 13. 22. 23. 11. 23. 23. 23. 15. 12. 16. 11. 12.
 17. 15. 19. 17. 19. 11. 18. 22. 19.  6. 22. 15. 13.  7. 16. 24. 18. 19.
 20. 24. 25. 18. 15. 12. 12. 14. 14. 28. 18. 23. 22. 23. 24. 11.  7. 15.
 14. 13. 11. 12. 22. 24. 21. 17. 24. 14. 20. 14.  6. 18. 13. 20. 26. 26.
 20. 19. 24.  7.  9. 22. 22. 16. 17. 21. 17. 23. 16. 16. 22.  8. 26. 14.
 17.  8. 23. 23. 19. 18. 22. 22. 20.  7. 21. 17. 11

In [76]:
most_rainday_cork = np.delete(most_rainday_cork, [-1])


In [77]:
print("The max most Rainfall in a Day : ", min(most_rainday_cork) )

The max most Rainfall in a Day :  3.0


In [104]:
print(most_rainday_cork[-1])

26.0


In [105]:
print(corkrain)

[[1.962e+03 1.000e+00 1.346e+02 1.250e+01 2.200e+01]
 [1.962e+03 2.000e+00 7.720e+01 1.120e+01 1.700e+01]
 [1.962e+03 3.000e+00 7.360e+01 1.340e+01 1.300e+01]
 ...
 [2.011e+03 1.000e+01 9.180e+01 2.440e+01 2.200e+01]
 [2.011e+03 1.100e+01 1.486e+02 3.520e+01 2.300e+01]
 [2.011e+03 1.200e+01 8.710e+01 2.200e+01 2.600e+01]]


In [117]:
a = np.arange(12).reshape((3, 4))
print(a)
b = np.array([[111, 1, 2, 3], [111, 4, 4, 5], [222, 1, 2, 3], [222, 3, 4, 5]])
for e in b: 
    print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[111   1   2   3]
[111   4   4   5]
[222   1   2   3]
[222   3   4   5]


In [123]:
num_sum = []
for e in b: 
    if e[0] == 222:
        num_sum.append(e[3])
        print(e[3])

3
5


In [125]:
print(np.sum(num_sum))

8


most_rainday_cork